### ISSUE TITLE
Improve "What implementations already exist?" list

### ISSUE THREAD

**Issue by zenorocha** [bevry-archive/gostatic#3]
Today, there are tons of static site generators, so you might wanna check @pinceladasdaweb's list to increase that list in the future.

https://github.com/pinceladasdaweb/Static-Site-Generators

:octocat: _Sent from [GH](http://nodegh.io)._

**Comment by balupton** [comment]
Sure. Perhaps lets do this only once pulling in the github stars dynamically, as otherwise we could get caught up in listing every one under the sun, which may not be that good. So in the meantime, lets just list the biggest.

**Comment by zenorocha** [comment]
Yeah, sure.
